site_name: Codesys Docs
site_description: Official documentation for CODESYS on ARMxy industrial edge gateways
site_url: https://beilai-technology.github.io/codesys/

plugins:
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: zh
          default: true
          name: 中文
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            首页: Home
            Codesys: Codesys
            说明书: Manual

theme:
  name: material
  custom_dir: overrides
  language: zh
  logo: assets/图片材料/钡铼技术英文logo.png
  favicon: assets/图片材料/钡铼技术英文logo.png
  palette:
    - scheme: default
      primary: light-blue
      accent: blue

nav:
  - 首页: index.md
  - Codesys:
      - 说明书: Codesys/Codesys说明书.md

extra_css:
  - assets/custom.css
